app/projects/models.py
from datetime import datetime

from app import db
from app.permissions import ProtectedMixin


class Release (db.Model):
    id = db.Column(db.Integer, primary_key=True)
    version = db.Column(db.String(20))
    description = db.Column(db.Text)
    file = db.relationship('File', uselist=False)
    date = db.Column(db.DateTime, default=datetime.now())

    project_id = db.Column(db.Integer, db.ForeignKey('project.id'))
    file_id = db.Column(db.Integer, db.ForeignKey('file.id'))

    def __init__(self, version, description, file):
        self.version = version
        self.description = description
        self.file = file

    def __repr__(self):
        return f'Release({self.id}, project_id={self.project_id}, {self.version})'


class Project (db.Model, ProtectedMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150))
    description = db.Column(db.Text)
    github = db.Column(db.String(1000), nullable=True)
    started = db.Column(db.DateTime, default=datetime.now())
    downloadable = db.Column(db.Boolean, default=False)

    releases = db.relationship(Release, lazy='dynamic', backref='project')

    def __init__(self, name, description):
        self.name = name
        self.description = description

    def __repr__(self):
        return f'Project({self.id}, {self.name})'

app/projects/__init__.py
from flask import Blueprint

from app import db
from app.projects.models import Project, Release
from app.admin_views import ProtectedModelView
from app.projects.admin_views import ProjectAdminView

bp = Blueprint('projects', __name__)


admin_views = [
    ProjectAdminView(Project, db.session, category="Projects"),
    ProtectedModelView(Release, db.session, category="Projects"),
]


from app.projects import routes

app/projects/routes.py
from flask import *

from app.projects import bp
from .models import Project, Release

from app.tools import model_view_function


@bp.route('/')
def index():
    projects = Project.query.all()
    return render_template("projects/list.html", projects=projects)


@bp.route('/<int:id>')
@model_view_function(Project)
def project(obj):
    latest = obj.releases.order_by(Release.date.desc()).first()
    return render_template("projects/project.html", project=obj, latest=latest)


@bp.errorhandler(404)
def error404(e):
    return render_template("projects/404.html"), 404

app/templates/projects/list.html
{% extends 'base.html' %}

{% block title %} Проекты {% endblock %}


{% block main %}

    <h1>Мои проекты</h1>

    <div class="content">
    {% if not projects %}
        <p>Список проектов пуст</p>
    {% endif %}
    {% for p in projects %}

        <div class="block">
            <h3>{{ p.name }}</h3>
            <p>{{ clean(p.description, [], strip=True)|truncate(50)|safe }}</p>
            <a href="{{ url_for('projects.project', id=p.id) }}" class="more">Подробнее</a>
        </div>

    {% endfor %}
    </div>

{% endblock %}

app/templates/projects/project.html
{% extends 'base.html' %}

{% block title %} Проект {% endblock %}


{% block head %}
    {{ super() }}
    {{ ckeditor.load_code_theme() }}
{% endblock %}


{% block main %}

    <h1>Проект &#171;{{ project.name }}&#187;</h1>

    <div class="content">
        <h2>Краткая информация</h2>
        <p>Дата начала проекта: {{ project.started.strftime('%d.%m.%Y') }}</p>
        {% if project.github %}
        <p>Исходный код проекта доступен на <a href="{{ project.github }}" target="_blank">github</a></p>
        {% endif %}
        {% if latest %}
        <p>Последняя версия: {{ latest.version }} ({{ latest.date.strftime('%d.%m.%Y') }})</p>
        {% endif %}

        <div class="content">
            <h2>Описание</h2>
            {{ project.description|safe }}
        </div>

        {% if latest %}
        <h2>Релизы</h2>
        <table class="bordered">
            <thead>
                <tr>
                    <th>Версия</th>
                    <th>Описание</th>
                    <th>Дата</th>
                    {% if project.downloadable %}
                    <th>Скачать</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            {% for release in project.releases|sort(attribute='date', reverse=True) %}
                <tr>
                    <td>{{ release.version }}</td>
                    <td>{{ release.description|safe }}</td>
                    <td>{{ release.date.strftime('%d.%m.%Y') }}</td>
                    {% if project.downloadable %}
                    {% if release.file %}
                    <td><a href="{{ url_for('main.download_file', filename=release.file.server_filename) }}">Скачать</a></td>
                    {% else %}
                    <td><b>Релиз нельзя скачать</b></td>
                    {% endif %}
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>

{% endblock %}