app/billing/models.py
import datetime

from app import db

from app.billing import p2p


class Account (db.Model):
    id = db.Column(db.Integer, primary_key=True)
    amount = db.Column(db.Integer, default=0)

    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    user = db.relationship("User", backref=db.backref("billing_account", uselist=False), uselist=False)

    @classmethod
    def create(cls, user):
        return cls(user=user)


class Bill (db.Model):
    id = db.Column(db.String(100), primary_key=True)
    amount = db.Column(db.Integer)
    url = db.Column(db.String(255))
    creation = db.Column(db.DateTime, default=datetime.datetime.now())
    status = db.Column(db.String(25), default="unknown")

    account_id = db.Column(db.Integer, db.ForeignKey("account.id"), nullable=False)
    account = db.relationship("Account", backref=db.backref("bills", lazy="dynamic"), lazy=True)

    @classmethod
    def create(cls, id, amount, url, account, creation, status):
        creation = datetime.datetime.fromisoformat(creation)
        return cls(id=id, amount=amount, url=url, account=account, creation=creation, status=status)

    def check(self):
        resp = p2p.check(self.id)
        print(resp.status)
        if self.status != resp.status:
            self.status = resp.status
            if self.status == "PAID":
                self.account.amount += self.amount
        db.session.commit()
        return self.status

app/billing/__init__.py
from flask import Blueprint
from pyqiwip2p import QiwiP2P


KEY = "eyJ2ZXJzaW9uIjoiUDJQIiwiZGF0YSI6eyJwYXlpbl9tZXJjaGFudF9zaXRlX3VpZCI6Ijc2O" \
        "GdxNy0wMCIsInVzZXJfaWQiOiI3OTE2OTkyMjIyOCIsInNlY3JldCI6ImU1MWIwNzNhYzNkND" \
        "UyOTFjODkxMWJiMzM2MTNlYTE2MmUxYTY3NjhiMjk2MTFlNzIyMjAzODM1YzA0MTlkY2QifX0="


bp = Blueprint("billing", __name__)
p2p = QiwiP2P(auth_key=KEY)


from app.billing import routes

app/billing/routes.py
from flask import *
from flask_login import login_required, current_user

from app import db
from app.billing import bp, p2p
from app.billing.models import Bill, Account


@bp.route("/")
@login_required
def account():
    if current_user.billing_account:
        account_bills = current_user.billing_account.bills.order_by(Bill.creation).all()
        return render_template("billing/account.html", account_bills=account_bills)
    return render_template("billing/account.html")


@bp.route("/payment", methods=["GET", "POST"])
@login_required
def payment():
    if not current_user.billing_account:
        return redirect(url_for("billing.account"))

    if request.method == "POST":
        amount = request.form.get("amount")
        if not amount:
            return render_template("billing/payment.html")

        resp = p2p.bill(amount=amount, currency="RUB", comment="Пополнение баланса brinzabezrukoff.xyz")
        bill = Bill.create(resp.bill_id, resp.amount, resp.pay_url, current_user.billing_account,
                           resp.creation, resp.status)
        db.session.add(bill)
        db.session.commit()
        return redirect(resp.pay_url)
    return render_template("billing/payment.html")


@bp.route("/open_account", methods=["POST"])
@login_required
def open_account():
    acc = Account.create(current_user)
    db.session.add(acc)
    db.session.commit()
    return redirect(url_for("billing.account"))

app/templates/billing/account.html
{% extends 'base.html' %}

{% block title %} Биллинг {% endblock %}

{% block main %}

    <h1> Биллинговый аккаунт </h1>
    <br>

    {% if not current_user.billing_account %}

        <p> У вас не открыт биллинговый аккаунт для совершения расчетов </p>

        <form action="{{ url_for('billing.open_account') }}" method="POST">
            <div class="row">
                <label>Принимаю пользовательское соглашение об использовании биллинга</label>
                <input type="checkbox" name="billing_terms" required>
            </div>
            <button type="submit"> Открыть биллинговый аккаунт </button>
        </form>

    {% else %}

        <h1> Баланс: {{ current_user.billing_account.amount }} RUB </h1>
        <a href="{{url_for('billing.payment')}}" target="_blank"><button type="button">Пополнить баланс</button></a>
        <br>
        <br>

        <h1> Список счетов на оплату: </h1>
        <table class="bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Дата</th>
                <th>Сумма</th>
                <th>Статус</th>
                <th>Оплата</th>
            </tr>
        </thead>
        <tbody>
            {% for bill in account_bills %}
                {% if bill.check() == "WAITING" %}
                <tr>
                    <td>{{ bill.id[22:] }}</td>
                    <td>{{ bill.creation.strftime('%d-%m-%Y %H:%M') }}</td>
                    <td>{{ bill.amount }}</td>
                    <td>{{ bill.status }}</td>
                    {% if bill.status == "WAITING" %}
                        <td><a href="{{ bill.url }}" target="_blank"><button>Оплатить</button></a></td>
                    {% else %}
                        <td>-</td>
                    {% endif %}
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
        </table>

    {% endif %}

{% endblock %}

app/templates/billing/payment.html
{% extends 'base.html' %}

{% block title %} Биллинг {% endblock %}

{% block main %}

    <h1> Пополнение баланса </h1>

    <form action="{{ url_for('billing.payment') }}" method="POST">
        <div class="row">
            <label>Сумма пополнения</label>
            <input type="text" name="amount" required>
        </div>

        <div class="row">
            <button type="submit">Выставить счет</button>
        </div>
    </form>

{% endblock %}